In [1]:
import pandas as pd

import numpy as np

from csynthpop import zone_synthesizer as zs

#### Specify sample data csv paths. See the files listed here for expected structure. Marginal tables require multi-indexed columns with category name and category value in levels 0 and 1 of the index. Sample file category columns should be labeled with corresponding category names and values in those columns should match the category value headers in the marginal table.

In [2]:
hh_marginal_file = './data/hh_marginals.csv'
person_marginal_file = './data/person_marginals.csv'
hh_sample_file = './data/household_sample.csv'
person_sample_file = './data/person_sample.csv'

In [3]:
def convert_to_str(margin, sample):
    colist = []
    for acol in margin.columns:
        colist.append(acol[0])
    colist = np.unique(colist)
    for acol in colist:
        if acol in sample.columns:
            sample[acol] = sample[acol].astype(str)
    return sample

#### Load and process input marginals and samples and geography crosswalk

In [4]:
hh_marg, p_marg, hh_sample, p_sample, xwalk = zs.load_data(hh_marginal_file, person_marginal_file, hh_sample_file, person_sample_file)

hh_sample = convert_to_str(hh_marg,hh_sample)
p_sample = convert_to_str(p_marg,p_sample)

Custom Synthpop!

In [19]:
xwalk

[(49.0, 1), (50.0, 1), (51.0, 1), (52.0, 1)]

In [5]:
hh_sample

            serialno  sample_geog  BEDRD  MRERD  RNTRD  STRD  VEHRD
0     CSF11B00068468           51      3     11     22     1      2
1     CSF11B00074011           50      5     21     22     1      2
2     CSF11B00074253           49      2     19     22     1      1
3     CSF11B00074820           51      2     21     12     1      1
4     CSF11B00075651           49      4     21     22     1      4
5     CSF11B00075690           49      4     13     22     1      4
6     CSF11B00075691           49      4     21     22     1      2
7     CSF11B00075692           49      7     21     22     6      6
8     CSF11B00075693           49      3     21     22     1      2
9     CSF11B00075694           49      3     21     22     1      2
10    CSF11B00075695           49      4     21     22     1      4
11    CSF11B00075696           49      4     21     22     1      2
12    CSF11B00075697           49      4     17     22     1      2
13    CSF11B00075698           49      5     21     22     1      3
14    CSF11B00075699           49      2     21     22     3      1
15    CSF11B00075700           49      3     21     22     1      2
16    CSF11B00075701           49      4     21     22     1      4
17    CSF11B00075702           49      7     21     22     6      6
18    CSF11B00075703           49      2     20     22     3      0
19    CSF11B00075704           49      1     21      2     3      5
20    CSF11B00075705           49      2     21     12     3      1
21    CSF11B00075706           49      3     21     18     2      2
22    CSF11B00075707           49      3     21     20     2      2
23    CSF11B00075708           49      2     18     22     1      1
24    CSF11B00075709           49      4     17     22     1      2
25    CSF11B00075710           49      3      8     22     2      2
26    CSF11B00075711           49      6     21     22     3      5
27    CSF11B00075712           49      2     21      4     2      1
28    CSF11B00075713           49      2     21     19     3      1
29    CSF11B00075714           49      6     21     22     3      5
...              ...          ...    ...    ...    ...   ...    ...
6563  CSF11B00082252           52      4     21     22     1      1
6564  CSF11B00082253           52      2     21     22     1      1
6565  CSF11B00082254           52      3     21     17     1      1
6566  CSF11B00082255           52      1     21     16     1      1
6567  CSF11B00082256           52      4     18     22     1      3
6568  CSF11B00082257           52      3     17     22     2      2
6569  CSF11B00082258           52      3      8     22     1      4
6570  CSF11B00082259           52      3     19     22     1      3
6571  CSF11B00082260           52      4      6     22     1      2
6572  CSF11B00082261           52      4     21     22     1      2
6573  CSF11B00082262           52      3     11     22     1      1
6574  CSF11B00082263           52      3     21     22     1      2
6575  CSF11B00082264           52      2     21      1     2      1
6576  CSF11B00082265           52      3     21     22     1      2
6577  CSF11B00082266           52      4     21     22     1      4
6578  CSF11B00082267           52      2     21     14     2      1
6579  CSF11B00082268           52      2     21     22     1      1
6580  CSF11B00082269           52      3     21     22     1      2
6581  CSF11B00082270           52      3     21     22     1      1
6582  CSF11B00082271           52      3     21     22     1      0
6583  CSF11B00082272           52      4      7     22     1      4
6584  CSF11B00082273           52      4     21     22     1      2
6585  CSF11B00082274           52      4      1     22     1      2
6586  CSF11B00082275           52      4     21     22     1      0
6587  CSF11B00082276           52      4     21     16     1      2
6588  CSF11B00082277           52      3     21     22     1      2
6589  CSF11B00082278           52      3      6     22     1      1
6590  CSF11B00082338           50      3     21      2     1      0
6591  CSF11B00082662           49      2     21      2     4      0
6592  CSF11B00082894           52      3     21      8     2      0

[6593 rows x 7 columns]

In [6]:
hh_marg = hh_marg.astype(int)
p_marg = p_marg.astype(int)

In [18]:
xwalk

[(49.0, 1), (50.0, 1), (51.0, 1), (52.0, 1)]

In [7]:
hh_marg.head()

cat_name   BEDRD                                      MRERD      ... STRD     \
cat_values     0    1    2     3     4    5    6    7     1   2  ...    4  5
49.0          14  162  586  1076   782  164  198  268    10   8  ...   24  2
50.0           8   74  330  1344  1492  196  178  100    28   6  ...   22  2
51.0          12   96  344  1344  1146  170  162  158    12  18  ...   16  0
52.0           8   72  298   928  1070  138  152  116    26   6  ...   26  2

cat_name        VEHRD
cat_values    6     0     1     2    3    4    5    6
49.0        268   246   996  1064  282  170  224  268
50.0        100   166  1080  1488  486  200  202  100
51.0        158   212  1022  1214  402  224  200  158
52.0        116   142   858  1000  312  188  166  116

[4 rows x 64 columns]

In [8]:
p_marg.head()

cat_name   INCP                                               ... RLHP       \
cat_values    1    2    3    4    5    6    7    8    9   10  ...    4    5
49.0         38  448  462  484  488  628  482  494  488  392  ...  382  364
50.0         42  566  522  674  600  766  668  644  656  512  ...  480  482
51.0         40  588  466  624  688  758  612  592  610  448  ...  400  506
52.0         28  480  368  458  492  594  484  456  462  384  ...  364  408

cat_name                                   SEXP
cat_values    6     7    8    9   10   11     1     2
49.0        142  1136  210  316  338  124  3794  3862
50.0        188  1106  220  288  110   96  4664  4944
51.0        188  1230  204  254  194   88  4256  4246
52.0        148   814  184  254  132   68  3424  3532

[4 rows x 68 columns]

In [9]:
p_sample.head()

         serialno  sample_geog  AGEP  INCP  INDP  LFSP  OCCP  RLHP  SEXP
0  CSF11B00068468           51    25     9    16     1     5     5     1
1  CSF11B00068468           51    36     5    22     3    10     6     2
2  CSF11B00068468           51    30     4    22     3    10     1     1
3  CSF11B00068468           51    29     5    22     3    10     1     2
4  CSF11B00068468           51    25     7    10     1     5     5     1

In [10]:
p_sample.columns

Index(['serialno', 'sample_geog', 'AGEP', 'INCP', 'INDP', 'LFSP', 'OCCP',
       'RLHP', 'SEXP'],
      dtype='object')

In [11]:
hh_sample.columns

Index(['serialno', 'sample_geog', 'BEDRD', 'MRERD', 'RNTRD', 'STRD', 'VEHRD'], dtype='object')

In [12]:
hh_sample

            serialno  sample_geog  BEDRD  MRERD  RNTRD  STRD  VEHRD
0     CSF11B00068468           51      3     11     22     1      2
1     CSF11B00074011           50      5     21     22     1      2
2     CSF11B00074253           49      2     19     22     1      1
3     CSF11B00074820           51      2     21     12     1      1
4     CSF11B00075651           49      4     21     22     1      4
5     CSF11B00075690           49      4     13     22     1      4
6     CSF11B00075691           49      4     21     22     1      2
7     CSF11B00075692           49      7     21     22     6      6
8     CSF11B00075693           49      3     21     22     1      2
9     CSF11B00075694           49      3     21     22     1      2
10    CSF11B00075695           49      4     21     22     1      4
11    CSF11B00075696           49      4     21     22     1      2
12    CSF11B00075697           49      4     17     22     1      2
13    CSF11B00075698           49      5     21     22     1      3
14    CSF11B00075699           49      2     21     22     3      1
15    CSF11B00075700           49      3     21     22     1      2
16    CSF11B00075701           49      4     21     22     1      4
17    CSF11B00075702           49      7     21     22     6      6
18    CSF11B00075703           49      2     20     22     3      0
19    CSF11B00075704           49      1     21      2     3      5
20    CSF11B00075705           49      2     21     12     3      1
21    CSF11B00075706           49      3     21     18     2      2
22    CSF11B00075707           49      3     21     20     2      2
23    CSF11B00075708           49      2     18     22     1      1
24    CSF11B00075709           49      4     17     22     1      2
25    CSF11B00075710           49      3      8     22     2      2
26    CSF11B00075711           49      6     21     22     3      5
27    CSF11B00075712           49      2     21      4     2      1
28    CSF11B00075713           49      2     21     19     3      1
29    CSF11B00075714           49      6     21     22     3      5
...              ...          ...    ...    ...    ...   ...    ...
6563  CSF11B00082252           52      4     21     22     1      1
6564  CSF11B00082253           52      2     21     22     1      1
6565  CSF11B00082254           52      3     21     17     1      1
6566  CSF11B00082255           52      1     21     16     1      1
6567  CSF11B00082256           52      4     18     22     1      3
6568  CSF11B00082257           52      3     17     22     2      2
6569  CSF11B00082258           52      3      8     22     1      4
6570  CSF11B00082259           52      3     19     22     1      3
6571  CSF11B00082260           52      4      6     22     1      2
6572  CSF11B00082261           52      4     21     22     1      2
6573  CSF11B00082262           52      3     11     22     1      1
6574  CSF11B00082263           52      3     21     22     1      2
6575  CSF11B00082264           52      2     21      1     2      1
6576  CSF11B00082265           52      3     21     22     1      2
6577  CSF11B00082266           52      4     21     22     1      4
6578  CSF11B00082267           52      2     21     14     2      1
6579  CSF11B00082268           52      2     21     22     1      1
6580  CSF11B00082269           52      3     21     22     1      2
6581  CSF11B00082270           52      3     21     22     1      1
6582  CSF11B00082271           52      3     21     22     1      0
6583  CSF11B00082272           52      4      7     22     1      4
6584  CSF11B00082273           52      4     21     22     1      2
6585  CSF11B00082274           52      4      1     22     1      2
6586  CSF11B00082275           52      4     21     22     1      0
6587  CSF11B00082276           52      4     21     16     1      2
6588  CSF11B00082277           52      3     21     22     1      2
6589  CSF11B00082278           52      3      6     22     1      1
6590  CSF11B00082338           50      3     21      2     1      0
6591  CSF11B00082662           49      2     21      2     4      0
6592  CSF11B00082894           52      3     21      8     2      0

[6593 rows x 7 columns]

In [13]:
xwalk[1]

(50.0, 1)

In [14]:
p_sample.dtypes

serialno       object
sample_geog     int64
AGEP            int64
INCP            int64
INDP            int64
LFSP            int64
OCCP            int64
RLHP            int64
SEXP            int64
dtype: object

In [15]:
hh_sample[hh_sample.sample_geog == xwalk[1]]

Empty DataFrame
Columns: [serialno, sample_geog, BEDRD, MRERD, RNTRD, STRD, VEHRD]
Index: []

In [16]:
xwalk

[(49.0, 1), (50.0, 1), (51.0, 1), (52.0, 1)]

#### Iterate over all marginals in the geography crosswalk and synthesize in-line

In [17]:
all_households, all_persons, all_stats = zs.synthesize_all_zones(hh_marg, p_marg, hh_sample, p_sample, xwalk)

sample df Empty DataFrame
Columns: [serialno, sample_geog, BEDRD, MRERD, RNTRD, STRD, VEHRD]
Index: []
cate df                               cat_id
BEDRD MRERD RNTRD STRD VEHRD
0     1     1     1    0           0
                       1           1
                       2           2
                       3           3
                       4           4
                       5           5
                       6           6
                  2    0           7
                       1           8
                       2           9
                       3          10
                       4          11
                       5          12
                       6          13
                  3    0          14
                       1          15
                       2          16
                       3          17
                       4          18
                       5          19
                       6          20
                  4    0          21
                       1          22
                       2          23
                       3          24
                       4          25
                       5          26
                       6          27
                  5    0          28
                       1          29
...                              ...
7     21    22    2    5      155202
                       6      155203
                  3    0      155204
                       1      155205
                       2      155206
                       3      155207
                       4      155208
                       5      155209
                       6      155210
                  4    0      155211
                       1      155212
                       2      155213
                       3      155214
                       4      155215
                       5      155216
                       6      155217
                  5    0      155218
                       1      155219
                       2      155220
                       3      155221
                       4      155222
                       5      155223
                       6      155224
                  6    0      155225
                       1      155226
                       2      155227
                       3      155228
                       4      155229
                       5      155230
                       6      155231

[155232 rows x 1 columns]
sample df Empty DataFrame
Columns: [serialno, sample_geog, AGEP, INCP, INDP, LFSP, OCCP, RLHP, SEXP]
Index: []
cate df                                cat_id
INCP INDP LFSP OCCP RLHP SEXP
1    1    1    1    1    1          0
                         2          1
                    2    1          2
                         2          3
                    3    1          4
                         2          5
                    4    1          6
                         2          7
                    5    1          8
                         2          9
                    6    1         10
                         2         11
                    7    1         12
                         2         13
                    8    1         14
                         2         15
                    9    1         16
                         2         17
                    10   1         18
                         2         19
                    11   1         20
                         2         21
               2    1    1         22
                         2         23
                    2    1         24
                         2         25
                    3    1         26
                         2         27
                    4    1         28
                         2         29
...                               ...
15   23   6    10   8    1     500910
                         2     500911
                    9    1     500912
                         2     500913
                    10   1     500914
                         2     500915
                    11   1     500916
                         2     500917
               11   1    1     500918
                         2     500919
                    2    1     500920
                         2     500921
                    3    1     500922
                         2     500923
                    4    1     500924
                         2     500925
                    5    1     500926
                         2     500927
                    6    1     500928
                         2     500929
                    7    1     500930
                         2     500931
                    8    1     500932
                         2     500933
                    9    1     500934
                         2     500935
                    10   1     500936
                         2     500937
                    11   1     500938
                         2     500939

[500940 rows x 1 columns]

ValueError: cannot insert VEHRD, already exists

In [ ]:
all_households.head()

In [ ]:
all_households.shape

In [ ]:
all_persons.shape

#### all_persons.household_id maps person records to all_households.index

In [ ]:
all_persons.head()

In [ ]:
all_stats